version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PURPUR
      VANILLATWEAKS_SHARECODE: "RP75rZ"
      MOTD: "\u00a7e\u00a7lMi\u0119dzyszkole SMP\u00a7r\\n\u00a761.19.4+ \u00a77Java + Bedrock"
      FORCE_GAMEMODE: true
      COPY_CONFIG_DEST: "/data"
      SYNC_SKIP_NEWER_IN_DESTINATION: false
      DIFFICULTY: "hard"
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      OPS: "a6395a8e-d178-4b6f-b03a-456578f08ea1"
      SNOOPER_ENABLED: false
      ICON: "https://media.discordapp.net/attachments/1061981328884650126/1094308816981594342/icon.png"
      OVERRIDE_ICON: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_NETHER: true
      MAX_PLAYERS: 80
      SPIGET_RESOURCES: "19254,27448,81534,85811,102931,34781,57272,79295,28140,1331,4047,44411,2124,845,101614,46229,6245"
      RCON_CMDS_STARTUP:  |-
        op sioodmy
        gamerule doInsomnia false
        gamerule spawnRadius 300
      VIEW_DISTANCE: 7
      SIMULATION_DISTANCE: 4
      NETWORK_COMPRESSION_THRESHOLD: 256
      SPAWN_PROTECTION: 0
      ONLINE-MODE: false
      MEMORY: 25G
    ports:
      - "25565:25565"
      - "19132:19132"
    volumes:
      - ./mc:/data
      - ./config:/config
      - ./plugins:/plugins
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
    volumes:
    - mc:/data:ro
    - ./mc-backups:/backups
    network_mode: "service:mc"
volumes:
  mc: {}