version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PURPUR
      VANILLATWEAKS_SHARECODE: "8pDzN4"
      MOTD: "\u00a7f\u00a7l1LO\u00a7e\u00a7l SMP \u00a7e\u00a7l\u00a7kkutasiak\u00a7r\n\u00a77\u22d9 half-anarchy \u00a7e\u00a7l1.19.4"
      FORCE_GAMEMODE: true
      COPY_CONFIG_DEST: "/data"
      SYNC_SKIP_NEWER_IN_DESTINATION: false
      OPS: "a6395a8e-d178-4b6f-b03a-456578f08ea1"
      SNOOPER_ENABLED: false
      ICON: "https://media.discordapp.net/attachments/980585755304931408/1091491664561983629/cropped.jpg"
      OVERRIDE_ICON: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_NETHER: true
      MAX_PLAYERS: 100
      SPIGET_RESOURCES: "19254,27448,81534,85811,102931,34781,57272,79295,28140,1331"
      VIEW_DISTANCE: 7
      SIMULATION_DISTANCE: 4
      NETWORK_COMPRESSION_THRESHOLD: 256
      SPAWN_PROTECTION: 0
      ONLINE-MODE: false
      MEMORY: 6G
    ports:
      - "25565:25565"
    volumes:
      - ./mc:/data
      - ./config:/config
      - ./plugins:/plugins
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
    volumes:
    - mc:/data:ro
    - ./mc-backups:/backups
    network_mode: "service:mc"

volumes:
  mc: {}